[tool.poetry]
name = "isabelle-deps"
version = "0.1.0"
description = ""
authors = ["sano <sano@ueda.info.waseda.ac.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
